FROM python:3.12-slim

WORKDIR /app

RUN pip install --no-cache-dir --timeout=300 --retries 10 \
    --trusted-host pypi.org \
    --trusted-host files.pythonhosted.org \
    fastapi uvicorn httpx

COPY docker_frontend/main_frontend.py .
COPY frontend/ frontend/

EXPOSE 80

CMD ["uvicorn", "main_frontend:app", "--host", "0.0.0.0", "--port", "80"]
